stages:
  - test
  - report

variables:
  REPORTPATH: 'C:\Users\FO009200\eclipse-workspace\Projeto_PIX\automation_test-autbankapi\target_'

RunTests:
  only:
    - master
  stage: test
  artifacts:
    paths:
      - reports/JavaRestAssuredTemplate
  tags:
    - test
  script:
    - echo %REPORTPATH%
    - mvn clean verify
  when: always
  allow_failure: true

SendReport:
  variables:
    GIT_CLEAN_FLAGS: none
  only:
    - master
  stage: report
  dependencies:
    - RunTests
  tags:
    - test
  when: always
  script:
    - set SourcePath $pwd'\target\reports\JavaRestAssuredTemplate'
    - set DestinationPath $REPORTPATH$env:CI_PIPELINE_ID
    - xcopy $SourcePath $DestinationPath /i/s