pool: Karen

#Your build pipeline references an undefined variable named ‘Parameters.mavenPOMFile’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- task: Maven@3
  displayName: 'Maven pom.xml'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test -Denv=qa -Dbrowser=chrome'
    testResultsFiles: 'target/xml-junit/*.xml'
    testRunTitle: 'Functional Testing'

- task: CmdLine@2
  inputs:
    script: |
      echo mvn clean verify