pool: Karen

#Your build pipeline references an undefined variable named ‘Parameters.mavenPOMFile’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- task: Maven@3
  displayName: 'Maven pom.xml'
  inputs:
    mavenPomFile: 'pom.xml' 
    publishJUnitResults: true 
    testResultsFiles: '**/surefire-reports/TEST-*.xml' # Required when publishJUnitResults == True
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    mavenVersionOption: Default
    mavenDirectory: 'C:\Program Files\apache-maven-3.6.3'
    mavenSetM2Home: true
    mavenAuthenticateFeed: false 
    effectivePomSkip: false 
    sonarQubeRunAnalysis: false 
    sqMavenPluginVersionChoice: 'latest'
  